const { Router } = require("express");
const questions = require("./questions");
const rating = require("./rating");
const users = require("./users");
const leaderboards = require("./leaderboards");
const authentication = require("./auth/authentication");
const api = Router();
api.use("/questions", questions);
api.use("/rating", rating);
api.use("/users", users);
api.use("/leaderboards", leaderboards);
api.use("/authentication", authentication);
module.exports = { api };
